export enum OrderStatus {
  NONE = 'NONE',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
